citasmedicas/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

task/urls.py
from django.urls import path 
from django.contrib.auth.decorators import login_required
from task import views
from .views import Inicio
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Inicio.as_view(), name='home'),
    path('salir/', views.salir, name='salir'), 
    path('perfilPaciente/<str:username>/', login_required(views.perfilPaciente), name='perfilPaciente'),
    path('perfilDoctor/<str:username>/', login_required(views.perfilDoctor), name='perfilDoctor'),
    
    #URLS CAMBIAR CONTRASEñA
    path('change_password/', login_required(views.ProfilePasswordChangeView.as_view()), name='change_password'),
  
    #URLS DE DOCTOR
    path('RegistroDoctor/',login_required(views.create_doctor),name='RegistroDoctor'),
    path('ListarDoctor/', login_required(views.ListaDoctores.as_view()) , name='ListarDoctor'),
    path('EditarDoctor/<int:pk>/',login_required( views.EditarDoctor.as_view()), name='EditarDoctor'),
    path('EliminarDoctor/<int:pk>/', login_required(views.EliminarDoctor.as_view()), name='EliminarDoctor'),
    path('EditarDoctorPerfil/<int:pk>/', login_required(views.EditarDoctorPerfil.as_view()), name='EditarDoctorPerfil'),
    
    #URLS DE PACIETE

    path('register/', views.register , name='register'),
    path('ListarPaciente/', login_required(views.ListaPacientes.as_view()) , name='ListarPaciente'),
    path('EliminarPaciente/<int:pk>/', login_required(views.EliminarPaciente.as_view()), name='EliminarPaciente'),
    path('EditarPaciente/<int:pk>/', login_required(views.EditarPaciente.as_view()), name='EditarPaciente'),
    path('EditarPacientePerfil/<int:pk>/', login_required(views.EditarPacientePerfil.as_view()), name='EditarPacientePerfil'),
    
    #URLS DE DISPONIBILIDAD DEL DOCTOR
    path('crear-disponibilidad/', login_required(views.crear_disponibilidad), name='crear-disponibilidad'),
    path('ver-disponibilidad/', login_required(views.ver_disponibilidad), name='ver_disponibilidad'),
    path("eliminar-disponibilidad/<int:pk>/", login_required(views.eliminar_disponibilidad), name="eliminar_disponibilidad"),
    path("modificar-disponibilidad<int:pk>/", login_required(views.modificar_disponibilidad), name="modificar_disponibilidad"),

    #URLS DE CITAS   
    #Paciente
    path('seleccionar-doctor/', views.seleccionar_doctor, name='seleccionar_doctor'),
    path('seleccionar-fecha/<int:doctor_id>/', views.seleccionar_fecha, name='seleccionar_fecha'),
    path('seleccionar-turno/<int:disponibilidad_id>/', login_required( views.seleccionar_turno), name='seleccionar_turno'),
    path('agendar-cita/<int:disponibilidad_id>/', login_required( views.agendar_cita), name='agendar_cita'),
    path('detalle-cita/<int:cita_id>/', login_required( views.detalle_cita), name='detalle_cita'),
    path('mis_citas/', login_required(views.mis_citas), name='mis_citas'),
    path('eliminar_cita/<int:cita_id>/',  login_required(views.eliminar_cita), name='eliminar_cita'),
    
    #Consultas
    path('consultas-paciente/', login_required(views.citas_atendidas_paciente), name='consultas_paciente'),
    path('detalle-cita-paciente/<int:cita_id>/', login_required(views.detalle_cita_paciente), name='detalle_cita_paciente'),
  
    #Doctor
    path('doctor/citas/',  login_required(views.citas_doctor), name='citas_doctor'),
    path('doctor/cita/<int:cita_id>/',  login_required(views.detalle_cita_doctor), name='detalle_cita_doctor'),
    path('doctor/eliminar_cita/<int:cita_id>/', login_required(views.eliminar_cita_doctor), name='eliminar_cita_doctor'),
    path('cita/<int:cita_id>/atender/',  login_required(views.atender_cita), name='atender_cita'),
    path('cita/<int:cita_id>/perdio/',  login_required(views.perdio_cita), name='perdio_cita'),
    


    #Historial
    path('doctor/historial',  login_required(views.doctor_historial), name='doctor_historial'),
    path('doctor/cita/historial/<int:cita_id>/',  login_required(views.detalle_cita_doctor_historial), name='detalle_cita_doctor_historial'),
    path('eliminar-cita-historial/<int:cita_id>/', login_required(views.eliminar_cita_historial), name='eliminar_cita_historial'),
    

    #RESPALDO Y RESTAURACION    
    path('db/', login_required(views.admin_db_view), name='adminBD'),
    path('backup/', login_required(views.database_backup), name='database_backup'),
    path('restore/', login_required(views.database_restore), name='database_restore'),
    
    #PDF
    path('cita/<int:cita_id>/pdf/', login_required(views.generar_pdf_cita), name='generar_pdf_cita'),
    path('generar_pdf_cita_doctor/<int:cita_id>/', login_required(views.generar_pdf_cita_doctor), name='generar_pdf_cita_doctor'),
           
]

task/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser

#Tablas como de bdd


#-----USUARIO-----
class CustomUser(AbstractUser):
    ncolegiom = models.CharField(max_length=20, unique=True,blank=True, null=True )
    telefono = models.CharField(max_length=25)
    direccion = models.CharField(max_length=255)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_users',  # Custom name for the reverse relation
        blank=True,
        help_text='The groups this user belongs to. A user can belong to multiple groups.'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_users',  # Custom name for the reverse relation
        blank=True,
        help_text='Specific permissions for this user.'
    )

#-----DISPONIBILIDAD DE DOCTOR-----
class DisponibilidadDoctor(models.Model):
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    fecha = models.DateField()
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    def obtener_turnos_disponibles(self):
        hoy = datetime.date.today()
        hora_inicio = datetime.datetime.combine(hoy, self.hora_inicio)
        hora_fin = datetime.datetime.combine(hoy, self.hora_fin)

        turnos_disponibles = []
        hora_inicio_turno = hora_inicio
        while hora_inicio_turno < hora_fin:
            hora_fin_turno = hora_inicio_turno + datetime.timedelta(hours=1)
            if hora_fin_turno > hora_fin:
                break
            turnos_disponibles.append(
                (hora_inicio_turno.time(), hora_fin_turno.time())
            )
            hora_inicio_turno = hora_fin_turno

        return turnos_disponibles
    
#--------CITA------
class Cita(models.Model):
    paciente = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='citas_programadas')
    fecha = models.DateField()
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    disponibilidad = models.ForeignKey(DisponibilidadDoctor, on_delete=models.CASCADE) 
    atendida = models.BooleanField(default=False)
    indicaciones = models.TextField(max_length=2000, blank=True, null=True)
    recipe = models.TextField(max_length=2000, blank=True, null=True)
    informe = models.TextField(max_length=10000, blank=True, null=True)
    falto = models.BooleanField(default=False)

task/views.py
import datetime
from django.utils import timezone
import json
import os
import shutil
from django.shortcuts import get_object_or_404, render, redirect  
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.contrib.auth import logout, login, authenticate,update_session_auth_hash
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from .forms import UserRegistrationForm,CitaForm, UploadFileForm
from django.contrib.auth.models import Group
from .models import CustomUser, Cita, DisponibilidadDoctor
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseBadRequest, HttpResponse
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from xhtml2pdf import pisa
from datetime import datetime as dt
from django.db.models import Q  # Importar Q para consultas complejas


#Para saber que tipo de usuario es y enviar a las vistas
def get_user_context(request):
    context = {
        'is_doctor': False,
        'is_patient': False,
        'is_admin': False,
    }

    if request.user.groups.filter(name='doctor').exists():
        context['is_doctor'] = True
    elif request.user.groups.filter(name='patient').exists():
        context['is_patient'] = True
    elif request.user.groups.filter(name='admin').exists():
        context['is_admin'] = True
  
    return context

class Inicio(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_doctor = False
        is_patient = False
        is_admin= False

        if self.request.user.groups.filter(name='doctor').exists():
            is_doctor = True
        elif self.request.user.groups.filter(name='patient').exists():
            is_patient = True
        elif self.request.user.groups.filter(name='admin').exists():
            is_admin = True

        context['is_admin'] = is_admin
        context['is_doctor'] = is_doctor
        context['is_patient'] = is_patient
      
        return context

def salir(request):
    logout(request)
    return redirect('home')

#CAMBIAR CONTRASENAS 
class ProfilePasswordChangeView(PasswordChangeView):
    template_name = 'perfil/change_password.html'
    success_url = reverse_lazy('change_password') 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = get_user_context(self.request) 
        context.update(user_context)
        context['password_changed'] = self.request.session.get('password_changed', False)
        return context

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        self.request.session['password_changed'] = True
        messages.success(self.request, 'Cambio de contraseña exitoso')
        return self.render_to_response(self.get_context_data(form=form))

 #   def form_invalid(self, form):
  #      messages.error(self.request, 'No se pudo cambiar la contraseña')
   #     return self.render_to_response(self.get_context_data(form=form))
    


# --------------------------- PACIENTES ---------------------------
#------Registrar Pacientes----

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        grupo = Group.objects.get(name="patient")

        if user_form.is_valid():
            user = user_form.save()
            user.groups.add(grupo)
            user.save()

            user = authenticate(
            username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password1'])
            login(request, user)
            return redirect('home')
        else:
           
            errors = user_form.errors
            print(errors)
            return render(request, 'registration/register.html', {'form': user_form, 'errors': errors})
   
    else:
        user_form = UserRegistrationForm()

    return render(request, 'registration/register.html', {
        'user_form': user_form,
    })

# -----Listar Pacientes ----
class ListaPacientes(ListView):
    model= CustomUser
    template_name='paciente/ListarPaciente.html'
    context_object_name= 'Usuario'
    paginate_by = 10  # Muestra 10 pacientes por página

    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()
    def get_queryset(self):
        return  CustomUser.objects.filter(groups__name='patient')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usuarios_list = self.get_queryset()
        paginator = Paginator(usuarios_list, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context[self.context_object_name] = page_obj
        return context
#-----EDITAR PACIENTE----
#admin
class EditarPaciente(UpdateView):
    model = CustomUser
    fields = ['first_name', 'last_name', 'telefono', 'email','direccion']  
    template_name = 'paciente/EditarPaciente.html' 
    success_url = reverse_lazy('ListarPaciente')   
    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    def form_valid(self, form):
        messages.success(self.request, "El paciente ha sido modificado exitosamente.")
        return super().form_valid(form)
    
class EditarPacientePerfil(UpdateView):
    model = CustomUser
    fields = ['first_name', 'last_name', 'telefono', 'email','direccion']  
    template_name = 'perfil/EditarPacientePerfil.html'
    def test_func(self):
        return self.request.user.groups.filter(name='patient').exists()
    def get_success_url(self):
        return reverse_lazy('perfilPaciente', kwargs={'username': self.request.user.username})  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        context.update(get_user_context(self.request)) 
        return context
    def form_valid(self, form):
        messages.success(self.request, "Editado exitosamente")
        return super().form_valid(form)      
     
#-----ELIMINAR PACIENTE----
class EliminarPaciente(DeleteView):
    model = CustomUser
    template_name = 'paciente/EliminarPaciente.html'  
    success_url = reverse_lazy('ListarPaciente')   
    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    def form_valid(self, form):
        messages.success(self.request, "El paciente ha sido eliminado exitosamente.")
        return super().form_valid(form)
#-----Perfil Paciente---
def perfilPaciente(request, username):
    if not (request.user.groups.filter(name="patient").exists() or request.user.groups.filter(name="admin").exists()):
     return redirect("home")
    
    user = get_object_or_404(CustomUser, username=username)
    context = get_user_context(request)
    context['user'] = user

    return render(request, 'perfil/perfilPaciente.html', context)



# ---------------------------DOCTORES ---------------------------

#------Registar Doctores---
def create_doctor(request):
        if not request.user.groups.filter(name="admin").exists():
                return redirect("home") 
               
        if request.method == 'POST':
           
            user_form = UserRegistrationForm(request.POST)
            grupo = Group.objects.get(name="doctor")

            if user_form.is_valid():
                user = user_form.save()
                user.groups.add(grupo)
                user.save()

                user = authenticate(
                username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password1'])
                return redirect('ListarDoctor')
            else:
           
                errors = user_form.errors
            return render(request, 'doctor/RegistroDoctor.html', {'form': user_form, 'errors': errors})
   
        else:
            user_form = UserRegistrationForm()

        return render(request, 'doctor/RegistroDoctor.html', {
            'user_form': user_form,
        })

# -----Listar Doctores ----
class ListaDoctores(ListView):
    model= CustomUser
    template_name='doctor/ListarDoctor.html'
    context_object_name= 'usuario'
    paginate_by = 10  # Muestra 10 pacientes por página 

    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()

    def get_queryset(self):
        return  CustomUser.objects.filter(groups__name='doctor')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usuarios_list = self.get_queryset()
        paginator = Paginator(usuarios_list, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context[self.context_object_name] = page_obj
        return context


#-----EDITAR DOCTOR----
class EditarDoctorPerfil(UpdateView):
    model = CustomUser
    fields = ['first_name', 'last_name', 'telefono', 'email','direccion','ncolegiom']  
    template_name = 'perfil/EditarDoctorPerfil.html'
    def test_func(self):
        return self.request.user.groups.filter(name='doctor').exists()
    def get_success_url(self):
        return reverse_lazy('perfilDoctor', kwargs={'username': self.request.user.username})  

task/templates/doctor/EditarDoctor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="max-width: 50%;">
  <div class="card shadow mb-4">
      <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">EDITAR DOCTOR</h6>
      </div>
      <div class="card-body">
     <form class="user" method="POST">
          {% csrf_token %}
           
        <div class="container-fluid">
          <div class="container-fluid">
            <div class="row justify-content-center">
              <div class="form-group col-md-9">
                <input type="text" class="form-control form-control-user text-center" id="username"
                 name="username" placeholder="Usuario..." value="{{ form.instance.username }}"> 
             
            </div>
            </div>
          
              <div class="row justify-content-center">
                <div class="form-group col-md-9">
                  <input type="text" class="form-control form-control-user text-center" id="id_first_name"
                   name="first_name" placeholder="Nombre..."    value="{{ form.instance.first_name }} "/>
                </div>
            </div>


            <div class="row justify-content-center">
              <div class="form-group col-md-9">
                <input type="text" class="form-control form-control-user text-center" id="id_last_name" 
                name="last_name"  placeholder="Apellido..."  value=" {{ form.instance.last_name }} "/>
              </div>
            </div>
            

            <div class="row justify-content-center">
              <div class="form-group col-md-9">
                <input type="tel" class="form-control form-control-user text-center" id="id_telefono" 
       name="telefono" placeholder="Numero de Telefono..." value="{{ form.instance.telefono }}"/>

            </div>
            </div>

            <div class="row justify-content-center">
              <div class="form-group col-md-9">
                <input type="email" class="form-control form-control-user text-center" id="id_email" 
                name="email"  placeholder="Email..." value="{{form.instance.email }} "/>
              </div>
            </div>

            <div class="row justify-content-center">
              <div class="form-group col-md-9">
                <input type="text" class="form-control form-control-user text-center" id="id_direccion" name="direccion"
                       placeholder="Direccion..."  value="{{ form.instance.direccion }} "/>
          </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group col-md-9">
                    <input type="text" class="form-control form-control-user text-center" id="id_ncolegiom" name="ncolegiom"
                           placeholder="Numero de registro del Colegio de Medicos..."   value="{{ form.instance.ncolegiom }} "/>
                </div>
              </div>
            <div class="row justify-content-center">
              <div class="col-md-9"> 
                <button type="submit" class="btn btn-primary btn-user btn-block">Guardar Cambios</button>
                  <a href="{% url 'ListarDoctor' %}" type="button" class="btn btn-danger btn-user btn-block">Cancelar</a> 
                  
              </div>
          </div>
          
        </div>
         
          </form>

      </div>
    </div>
</div>
{% endblock content %}

task/templates/doctor/EliminarDoctor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center mt-5"> <!-- Agregamos una fila y centramos el contenido verticalmente -->
    <div class="col-md-6"> <!-- Establecemos el ancho de la columna -->
      <div class="card shadow mb-4">
          <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">ELIMINAR DOCTOR</h6>
          </div>
          <div class="card-body">
            <div class="row justify-content-center">
              <div class="form-group">
            <p>¿Estás seguro de que quieres eliminar este doctor?</p>

              <form class="user" method="POST">
                  {% csrf_token %}
                  <div class="row justify-content-center">
                    <div class="form-group col-md-9">
                        <div class="row">
                   <input type="hidden" name="pk" value="{{ object.pk }}">
                   <div class="col-md-6">
                    <a href="{% url 'ListarDoctor' %}" type="button" class="btn-user btn btn-primary btn-block">Cancelar</a> 

                   </div>
                  <div class="col-md-6">
                    <button type="submit" class="btn-user btn btn-danger btn-block" >Eliminar</button>

                  </div>
                      </div>
                    </div>
                  </div>
              </form>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

task/templates/doctor/RegistroDoctor.html
{% extends 'base.html' %}  
{% load static %}
{% block content %}

<div class="container-fluid" style="max-width: 50%;">
  <div class="card shadow mb-4">
      <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">REGISTRAR DOCTOR</h6>
        
      </div>
      <div class="card-body">
        <form class="user" method="POST">
          {% csrf_token %}
        <div class="container-fluid">
            
          <div class="form-group">
              <input type="text" class="form-control form-control-user" id="id_username" name="username"
                     placeholder="Usuario..." required value="{{ form.username.value }}">
              {% if form.errors.username %}
                  <p class="text-danger">{{ form.errors.username }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="text" class="form-control form-control-user" id="id_first_name" name="first_name"
                     placeholder="Nombre..." required value="{{ form.first_name.value }}">
              {% if form.errors.first_name %}
                  <p class="text-danger">{{ form.errors.first_name }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="text" class="form-control form-control-user" id="id_last_name" name="last_name"
                     placeholder="Apellido..." required value="{{ form.last_name.value }}">
              {% if form.errors.last_name %}
                  <p class="text-danger">{{ form.errors.last_name }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="email" class="form-control form-control-user" id="id_email" name="email"
                     placeholder="Email..." required value="{{ form.email.value }}">
              {% if form.errors.email %}
                  <p class="text-danger">{{ form.errors.email }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="tel" class="form-control form-control-user" id="id_telefono" name="telefono"
                     placeholder="Numero de Telefono..." required value="{{ form.telefono.value }}">
              {% if form.errors.telefono %}
                  <p class="text-danger">{{ form.errors.telefono }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="text" class="form-control form-control-user" id="id_direccion" name="direccion"
                     placeholder="Direccion..." required value="{{ form.direccion.value }}">
              {% if form.errors.direccion %}
                  <p class="text-danger">{{ form.errors.direccion }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="text" class="form-control form-control-user" id="id_ncolegiom" name="ncolegiom"
                     placeholder="Numero de registro del Colegio de Medicos..." required value="{{ form.ncolegiom.value }}">
              {% if form.errors.ncolegiom %}
                  <p class="text-danger">{{ form.errors.ncolegiom }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="password" class="form-control form-control-user" id="id_password1" name="password1"
                     placeholder="Contraseña..." required>
              {% if form.errors.password1 %}
                  <p class="text-danger">{{ form.errors.password1 }}</p>
              {% endif %}
          </div>
          <div class="form-group">
              <input type="password" class="form-control form-control-user" id="id_password2" name="password2"
                     placeholder="Confirme Contraseña..." required>
              {% if form.errors.password2 %}
                  <p class="text-danger">{{ form.errors.password2 }}</p>
              {% endif %}
          </div>

          <button type="submit" class="btn btn-primary btn-user btn-block">Registrar</button>
          <a href="{% url 'ListarDoctor' %}" type="button" class="btn btn-danger btn-user btn-block">Cancelar</a> 
          
         
        </div> 
      </form>
</div>
</div>


{% endblock %}